# Generated by Django 3.0.8 on 2020-08-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200809_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='one_click_puchasing',
            new_name='one_click_purchasing',
        ),
    ]
