# Generated by Django 3.0.8 on 2020-08-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shawls'), ('G', 'Gowns'), ('SC', 'Scarfs'), ('D', 'Decor'), ('SF', 'Saffron'), ('H', 'Honey'), ('T', 'Tea'), ('DF', 'Dry-Fruits')], max_length=2),
        ),
    ]
